### ISSUE TITLE
Replace "One place for all jobs" with "Un singur loc pentru toate locurile de munca"

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#1]
Expected results:
1.From the main page, replace "One place for all jobs" with "Un singur loc pentru toate locurile de munca"

**Comment by sergiuavram** [comment]
fixed in v0.14

**Comment by sebiboga** [comment]
@sergiuavram sorry I didn't say earlier
we want to have diacritics and to write in romanian everything we can
therefore we need diacritics here in title also

can you please update to:
  Un singur loc pentru toate locurile de muncă

**Comment by sergiuavram** [comment]
updated in v0.16

**Comment by sebiboga** [comment]
retested on PROD environment
this issue has been fixed
closing the bug

thank you @sergiuavram  and @ersiniakiss
