### ISSUE TITLE
unexpected character in title for job at Yardi and Utilben

### ISSUE THREAD

**Issue by sebiboga** [shaqo-doon/testing#12]
PROD
![image](https://user-images.githubusercontent.com/41440889/106354803-ff556800-62fc-11eb-8513-657e59fc2191.png)

**Comment by sebiboga** [comment]
same issue - Utilben 
![image](https://user-images.githubusercontent.com/41440889/106355439-86f0a600-6300-11eb-88ab-598093c1c308.png)

**Comment by sergiuavram** [comment]
solved this on v0.19.

I added a new bug when scrolling, ignore it for now :)

**Comment by sebiboga** [comment]
oh sorry :) I added a duplicate then for scrolling. I'm really sorry for that. 
no worries, once you fix the scroll on sticky menu, I'll close it

**Comment by sebiboga** [comment]
retested the issue on PROD environment
this issue has been fixed
closing the bug

thanks @sergiuavram
