### ISSUE TITLE
URL of the companies page is not displayed correctly

### ISSUE THREAD

**Issue by tonisfr** [shaqo-doon/testing#14]
STEPS TO REPRODUCE:

1. access shaqodoon.ro.
2. click on "Toate locurile de muncă" button.

EXPECTED RESULT:

URL of the page should be shaqodoon.ro/companii.

ACTUAL RESULT:

URL of the page is shaqodoon.ro/companies.

**Comment by sebiboga** [comment]
yes. indeed. it's not a functional issue.
this have impact to SEO (Search Engine Optimization)
the link will be presented later on in sitemap.xml that we will generate on 9 February 2021

@sergiuavram if you can make the update in the next release please

**Comment by sergiuavram** [comment]
change url from English to Romanian v0.20

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
