### ISSUE TITLE
sticky menu is not working properly on scroll

### ISSUE THREAD

**Issue by sebiboga** [shaqo-doon/testing#17]
Environment: PROD
  URL: https://shaqodoon.ro/companies
   browser: Chrome

Steps to reproduce:
 1) open URL in browser
 2) scroll down
 3) check the menu section

Expected results:
   the sticky menu came into action and old menu dissapear

Actual results:
   sticky meny is visible but old menu is still seen overlapping

![image](https://user-images.githubusercontent.com/41440889/106380695-bf55ba00-63bc-11eb-9fe2-fd65bc42c997.png)

**Comment by sergiuavram** [comment]
removed sticky option in  v0.20

**Comment by sebiboga** [comment]
so decision was on scroll not to be resized (the header) but the sticky remains.
we'll need to re-arrange the header in order to have much space for jobs and companies as @tonisfr suggested;
for MVP this is fine. 
adding the Milestone for Release version 1.0.0

**Comment by sebiboga** [comment]
retested on PROD and found this was fixed.
closing the bug
