### ISSUE TITLE
Bugs for 3 Pillar Global : "USA" is not typed correctly

### ISSUE THREAD

**Issue by tonisfr** [shaqo-doon/testing#19]
Environment: PROD
URL: https://shaqodoon.ro/jobs/3-Pillar-Global
browser: Chrome

STEPS TO REPRODUCE:

1. open URL in browser
2. scroll down

EXPECTED RESULT:
country should be typed USA

ACTUAL RESULT:
country is typed U.S.

**Comment by sebiboga** [comment]
fixed;

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
