### ISSUE TITLE
Replace "job-uri" with "locuri de munca" in "2362 job-uri"

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#2]
Expected results:
1.On the main page, replace "2362 job-uri" with " 2362 locuri de munca ".

**Comment by sergiuavram** [comment]
fixed in v0.14

**Comment by sebiboga** [comment]
retested; it's better but I should have say earlier we want diacritics in this project
please update the text to:
 locuri de muncă

**Comment by sergiuavram** [comment]
updated in v0.16

**Comment by sebiboga** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
