### ISSUE TITLE
After the name of the city is a space before the comma

### ISSUE THREAD

**Issue by ElisabetaGGherca** [shaqo-doon/testing#22]
STEPS TO REPRODUCE:

1. access shaqodoon.ro or zimbor.go.ro
2. click on "Companii" button
3. select a company 

EXPECTED RESULT:

The city is followed by the comma without space.

ACTUAL RESULT:
![image](https://user-images.githubusercontent.com/37840490/106395050-bab6f300-6408-11eb-8cdb-f6c81e8fa481.png)

**Comment by sergiuavram** [comment]
solved v0.22
