### ISSUE TITLE
Centering the content and the header when the browser shrinks

### ISSUE THREAD

**Issue by ElisabetaGGherca** [shaqo-doon/testing#25]
STEPS TO REPRODUCE:

1. access shaqodoon.ro or zimbor.go.ro on desktop full  screen
2. click on maximize/restore down button

EXPECTED RESULT:

Header and content to be centered when the browser shrinks.

ACTUAL RESULT:
![image](https://user-images.githubusercontent.com/37840490/106745953-81f66400-662a-11eb-8f0f-f526aaff74c1.png)

**Comment by sergiuavram** [comment]
solved v0.24
