### ISSUE TITLE
Homepage - correction of text and add diacritics

### ISSUE THREAD

**Issue by ElisabetaGGherca** [shaqo-doon/testing#26]
STEPS TO REPRODUCE:

1. access shaqodoon.ro or zimbor.go.ro

EXPECTED RESULT:

The text should be written correctly and with diacritics.

ACTUAL RESULT:
![image](https://user-images.githubusercontent.com/37840490/107212229-518a3d80-6a0f-11eb-996d-13bc2c4c00c6.png)

**Comment by sergiuavram** [comment]
solved v0.34
