### ISSUE TITLE
Replace "Jobs" button with "Locuri de munca"

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#3]
Expected results:
On the main page replace the "Jobs" button with "Locuri de munca".

**Comment by sergiuavram** [comment]
fixed in v0.14

**Comment by sebiboga** [comment]
please update the text to:
locuri de muncă

**Comment by sergiuavram** [comment]
updated in v0.16

**Comment by sebiboga** [comment]
retested in PROD environment
this issue has been fixed
closing the bug
