### ISSUE TITLE
Bugs for 3 Pillar Global company: country is missing

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#5]
Steps to reproduce:
1.From the main page, click on "Companies".
2.Then click on 3 Pillar Global, https://www.shaqodoon.ro/jobs/3-Pillar-Global

Actual results:
For all jobs country name is missing.

Expected results:
Country name should be added for each job entry after the city name.

**Comment by sebiboga** [comment]
![image](https://user-images.githubusercontent.com/41440889/106381252-2032c180-63c0-11eb-8131-579c46d8aed7.png)

**Comment by sebiboga** [comment]
updated the crawler; re-run the script;
please retest; if happy, please close the bug

**Comment by sebiboga** [comment]
@tonisfr please retest; if happy, close the issue

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
