### ISSUE TITLE
Bugs for 3 Pillar Global : Cluj Napoca is not typed correctly

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#6]
Steps to reproduce:
1.From the main page, click on "Companies".
2.Then click on 3 Pillar Global, https://www.shaqodoon.ro/jobs/3-Pillar-Global

Actual results:
 "Cluj Napoca" is missing a "-".

Expected results:
"Cluj Napoca" should be replaced with "Cluj-Napoca"

**Comment by sergiuavram** [comment]
This has to be update in the backend or database

**Comment by sebiboga** [comment]
updated with the previous fix;
@tonisfr please retest; if happy, close the bug

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
