### ISSUE TITLE
Bugs for 3 Pillar Global company: "Ia?i" is misstyped

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#7]
Steps to reproduce:
1.From the main page, click on "Companies".
2.Then click on 3 Pillar Global, https://www.shaqodoon.ro/jobs/3-Pillar-Global

Actual results:
"Ia?i" is misstyped.

Expected results:
"Ia?i" should be replaced with "Iaşi"

**Comment by sergiuavram** [comment]
This has to be update in the backend or database

**Comment by sebiboga** [comment]
fixed with prevous bug;
@tonisfr please retest; if happy, close the issue

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
