### ISSUE TITLE
Bugs for 3 Pillar Global : "Timisoara" is not typed with diacritics

### ISSUE THREAD

**Issue by ersiniakiss** [shaqo-doon/testing#8]
Steps to reproduce:
1.From the main page, click on "Companies".
2.Then click on 3 Pillar Global, https://www.shaqodoon.ro/jobs/3-Pillar-Global

Actual results:
"Timisoara" is mistyped, does not have diacritics

Expected results:
"Timisoara" should be replaced with "Timişoara".

**Comment by sergiuavram** [comment]
this has to be modified in the backend or database

**Comment by sebiboga** [comment]
fixed in backend;
please retest; if happy, close the issue
@tonisfr

**Comment by tonisfr** [comment]
retested on PROD environment
this issue has been fixed
closing the bug
